# This plugin has been created by Bosternike (Discord: Bosternike#7428).
#
# COMMANDS:
# /bosterchat - main plugin command.
#
# PERMISSIONS:
# /bosterchat - boster.chat.command
# /bosterchat reload - boster.chat.command.reload
# /bosterchat help - boster.chat.command.help
# /bosterchat <command> - boster.chat.command.<command>
#
# /chatcolor - boster.chat.chatcolor
# /chatcolor (unlimited chatcolors) - boster.chat.chatcolor.unlimited
# /chatcolor [color] [player] - boster.chat.chatcolor.others

# Storages:
# - YAML
# - SQLITE
# - MYSQL
Storage: YAML

MySql:
  host: 'localhost'
  port: 3306
  user: ''
  password: ''
  database: ''

Placeholders:
  NoClan: ''
  NoTown: ''
  NoNation: ''

Prefix: '&d&lBosterChat &8&l|'

# Command - /chatcolor
# Command usage - /chatcolor [color]
# Example usage - /chatcolor &6
# Another example usage - /chatcolor smart:a;b;c
ChatColor:
  Enabled: true
  name: 'chatcolor'
  aliases:
  - 'cc'
  # Argument to disable own chat color.
  # Example command usage - /chatcolor off
  DisableArgument: 'off'
  Patterns:
    # Command usage /chatcolor rgb
    rgb: 'rgb:255,255,0;255,0,255' # Returns rgb message.
    # Command usage /chatcolor triple
    triple: 'smart:a,b,c'
    # Command usage /chatcolor example
    example: 'smart:a,b,c,d,6'
    # Command usage /chatcolor half
    half: 'a|6'
    # Command usage /chatcolor half-rgb
    half-rgb: 'rgb|smart:a,b,c'
    # Command usage /chatcolor random
    random: 'random:0,1,2,3,4,5,6,7,8,9,a,b,c,d,e,f,k,l,m,n,o'
    # Command usage /chatcolor randomChar
    randomChar: 'randomChar:0§l,1§l,2§l,3§l,4§l,5§l,6§l,7§l,8§l,9§l,a§l,b§l,c§l,d§l,e§l,f§l,k§l,l§l,m§l,n§l,o§l'
  # Permission: boster.chat.chatcolor.<permission>
  limitedPermissions:
    # Permission: boster.chat.chatcolor.example
    example:
      # For all color codes use: ALL
      # List of color codes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, a, b, c, d, e, f, k, l, m, n, o
      ColorCodes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
      Patterns:
      - 'rgb'
      - 'triple'
      - 'example'
      - 'half'
      - 'half-rgb'
      - 'random'
      - 'randomChar'
      # Here can be patterns, color codes, etc.
      # Example command usage - /chatcolor smart:a;b;c
      Others:
      - 'smart:a;b;c'

# Command usage - /chatsettings help
ChatSettings:
  Enabled: true
  PermissionRequirement:
    Enabled: false
    perm: 'boster.chat.settings'
  name: chatsettings
  aliases:
  - csettings

Settings:
  # All following settings can be configured in chat settings.
  # End messages with dot?
  DotInsertion:
    Enabled: true
    PermissionRequirement:
      Enabled: true
      Permission: 'boster.chat.dot'
  # Should the first character of message be capital?
  CapitalizeMessage:
    Enabled: true
    PermissionRequirement:
      Enabled: true
      Permission: 'boster.chat.capitalize'
  # Should player be able to use color code (like &)?
  ColorizeMessage:
    Enabled: true
    PermissionRequirement:
      Enabled: true
      Permission: 'boster.chat.color'
  # Check for messages similarity.
  CheckSimilarity:
    Enabled: true
    # Similarity in percents.
    # If messages similarity >= 80%, message will be rejected.
    Similarity: 80
    Message:
    - '&cYour messages are too similar.'
  # Check for exact words.
  DeniedWords:
    # Permission to override this check.
    OverridePermission:
      Enabled: false
      Permission: 'boster.chat.denied.words.override'
    Enabled: true
    list:
    - 'fuck'
    Result:
      # It will replace each character of the word with the following symbol.
      replaceChars: '*'
  # Check if message contains any of the following list.
  DeniedContents:
    # Permission to override this check.
    OverridePermission:
      Enabled: false
      Permission: 'boster.chat.denied.contents.override'
    Enabled: true
    list:
    - 'fuckx'
    Result:
      message:
      - "&cSuch contents as '%content%' are disallowed."
  DenyAddress:
    Enabled: true
    # Permission to override this check.
    OverridePermission:
      Enabled: false
      Permission: 'boster.chat.deny.address.override'
    Result:
      # It will replace the whole IP with the following word.
      # WARNING: Result "replaceChars" IS NOT SUPPORTED!
      replace: 'your.server.net'

CooldownFormat:
  second: 'second'
  some_seconds: 'seconds'
  seconds: 'seconds'
  minute: 'minute'
  some_minutes: 'minutes'
  minutes: 'minutes'
  hour: 'hour'
  some_hours: 'hours'
  hours: 'hours'
  day: 'day'
  some_days: 'days'
  days: 'days'
CooldownMessage:
  Message:
    Enabled: true
    text: '&dBosterChat &8| &fWait &6%time%&f before using it again.'
  Title:
    Enabled: false
    text: '&fCooldown!'
  SubTitle:
    Enabled: false
    text: '&dBosterChat &8| &fWait &6%time%&f before using it again.'
  Actionbar:
    Enabled: true
    text: '&dBosterChat &8| &fWait &6%time%&f before using it again.'

Messages:
  noPermission: "%prefix% &cYou don't have permission to this command!"
  noArgs: '%prefix% &fType &d/bosterchat help &ffor help!'
  reload: '%prefix% &fThe plugin has been reloaded!'
  invalidSyntax: '%prefix% &fWrong syntax&7: &c%syntax%'
  nullPlayer: '%prefix% &fPlayer &c%arg%&f could not be found.'
  help:
  - '&f'
  - '&f &dBosterChat &7> &6Help'
  - '&f Reload the plugin &7- &d/bosterchat reload'
  - '&f Chat info &7- &d/bosterchat info [chat]'
  - '&f Player profile &7- &d/bosterchat profile [player]'
  - ''
  - '&f Set own chat color &7- &d/chatcolor [color]'
  - '&f Set chat color for other player &7- &d/chatcolor [color] [player]'
  - '&f Chat settings help &7- &d/chatsettings help'
  - '&f'
  profile:
    usage: '%prefix% &fUsage &7- &d/bosterchat player-info [player]'
  chatColor:
    usage: '%prefix% &fUsage &7- /chatcolor [color]'
    limit: "%prefix% &cYou don't have permission for unlimited chat colors."
    noPermissionOthers: "%prefix% &cYou don't have permission to change chat color for other players."
    set-self: '%prefix% &fYour chat color has been set to %color%&f!'
    set-others: "%prefix% &a%player%&f's chat color has been set to %color%&f!"
    off-self: '%prefix% &fYour chat color has been removed!'
    off-others: "%prefix% &a%player%&f's chat color has been removed!"
  chatSettings:
    help:
    - '&f'
    - "&f Disable chat (you won't receive messages from this chat) &7- &d/chatsettings disable [chat]"
    - '&f Enable chat (you will receive messages from this chat) &7- &d/chatsettings enable [chat]'
    - '&f'
    noChat: '%prefix% &fChat &c%name%&f could not be found.'
    chatDisabled: '%prefix% &fThis chat is &cdisabled&f for you.'
    disable:
      usage: '%prefix% &fUsage &7- &d/chatsettings disable [chat]'
      already: '%prefix% &fThis chat already disabled for you.'
      success: '%prefix% &fChat &a%name%&f has been &cdisabled&f for you.'
    enable:
      usage: '%prefix% &fUsage &7- &d/chatsettings enable [chat]'
      already: '%prefix% &fThis chat already enabled for you.'
      success: '%prefix% &fChat &a%name%&f has been &aenabled&f for you.'




      